# Generated by Django 3.1.4 on 2021-05-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(default='B', max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='../media/james.jpg', upload_to='face')),
            ],
        ),
    ]
